name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.31
        env:
            DB_CONNECTION_TEST: mysql
            DB_HOST_TEST: 127.0.0.1
            DB_PORT_TEST: 3306
            DB_DATABASE_TEST: aisha_test
            DB_USERNAME_TEST: root
            MYSQL_ROOT_PASSWORD: 123
            DB_PASSWORD_TEST: 123
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1.9'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3800
        container port: 3307
        character set server: 'utf8'
        collation server: 'utf8_general_ci'
        mysql version: '8.0'
        mysql database: 'test'
        mysql user: 'developer'
        mysql password: ${{ secrets.DatabasePassword }}
    - name: migration
      run: php artisan migrate --database="mysql_testing"
    - name: testing
      run: php artisan test
